module.exports=[
    require(`./control`),
    require(`./eventer`),   
    require(`./creative`), 
    require(`./clanstaff`), 
    require(`./closemod`), 
    require(`./mafia`),
    require(`./bunker`),
    require(`./kontenter`),
]