module.exports=[
    require(`./control`),
    require(`./eventer`),
    require(`./vedushiy`),
    require(`./closer`),
    require(`./creative`),
    require(`./clanstaff`),
    require(`./kontentes`),
    require(`./helper`),
]