module.exports=[
    require(`./control`),
    require(`./eventer`),
    require(`./vedushiy`),
    require(`./closer`),
    require(`./manager`),
    require(`./creative`),
    require(`./clanstaff`),
]