module.exports=[
    require(`./loveroom`),
    require(`./nitro`),
    require(`./oblako`),
    require(`./kartinki`),
    require(`./duber`),
    require(`./muz`),
    require(`./hudojka`),
    require(`./chtets`),
    require(`./selfi`),
]